-- +goose Up
-- +goose StatementBegin
CREATE TABLE USERS (
	id SERIAL PRIMARY KEY,
	username TEXT NOT NULL UNIQUE
);
CREATE TABLE QUIZ (
	id SERIAL PRIMARY KEY,
	title TEXT NOT NULL UNIQUE,
	description TEXT NOT NULL,
	owner_id INTEGER NOT NULL REFERENCES USERS(id)
);
CREATE TABLE QUESTION (
	id SERIAL PRIMARY KEY,
	quiz_id INTEGER NOT NULL REFERENCES QUIZ(id),
	question_text TEXT NOT NULL,
	score INTEGER NOT NULL
);
CREATE TABLE ANSWER_OPTION (
	id SERIAL PRIMARY KEY,
	question_id INTEGER NOT NULL REFERENCES QUESTION(id),
	answer TEXT NOT NULL,
	is_correct BOOLEAN NOT NULL
);
CREATE TABLE QUIZ_RESPONSE (
	id SERIAL PRIMARY KEY,
	quiz_id INTEGER NOT NULL REFERENCES QUIZ(id),
	user_id INTEGER NOT NULL REFERENCES USERS(id),
	score INTEGER NOT NULL
);
CREATE TABLE QUESTION_RESPONSE (
	id SERIAL PRIMARY KEY,
	quiz_response_id INTEGER NOT NULL REFERENCES QUIZ_RESPONSE(id),
	answer_option_id INTEGER NOT NULL REFERENCES ANSWER_OPTION(id)
);
-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin
DROP TABLE USERS;
-- +goose StatementEnd
